// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYL1nxXhNM8vcjxlnK9CRV9UmNkf1LYUI',
    appId: '1:362187059839:web:232d808527feb68c4ec54a',
    messagingSenderId: '362187059839',
    projectId: 'stylish-app-78c6e',
    authDomain: 'stylish-app-78c6e.firebaseapp.com',
    storageBucket: 'stylish-app-78c6e.firebasestorage.app',
    measurementId: 'G-QS84K6BM13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDVwZl_P7MPqsBPRRTvMw8V7EYvM9lqZE',
    appId: '1:362187059839:android:030ace8abe909d194ec54a',
    messagingSenderId: '362187059839',
    projectId: 'stylish-app-78c6e',
    storageBucket: 'stylish-app-78c6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaowpIQFmGD7DXwUNMeDEE0aIF_ff0WgY',
    appId: '1:362187059839:ios:083e4077b0d9bcd54ec54a',
    messagingSenderId: '362187059839',
    projectId: 'stylish-app-78c6e',
    storageBucket: 'stylish-app-78c6e.firebasestorage.app',
    iosBundleId: 'com.example.stylishApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaowpIQFmGD7DXwUNMeDEE0aIF_ff0WgY',
    appId: '1:362187059839:ios:083e4077b0d9bcd54ec54a',
    messagingSenderId: '362187059839',
    projectId: 'stylish-app-78c6e',
    storageBucket: 'stylish-app-78c6e.firebasestorage.app',
    iosBundleId: 'com.example.stylishApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYL1nxXhNM8vcjxlnK9CRV9UmNkf1LYUI',
    appId: '1:362187059839:web:dea48048f2492aa74ec54a',
    messagingSenderId: '362187059839',
    projectId: 'stylish-app-78c6e',
    authDomain: 'stylish-app-78c6e.firebaseapp.com',
    storageBucket: 'stylish-app-78c6e.firebasestorage.app',
    measurementId: 'G-9VZYJE6BTE',
  );
}
